import { colors } from './colors';

export const categoryTheme = {
  Vehicles: colors.secondaryLightGradient,
  RealEstate: colors.primaryLightGradient,
  Electronics: colors.greenLightGradient,
  Furniture: colors.grayLightGradient,
  Jobs: colors.indigoLightGradient,
  Services: colors.redLightGradient,
  Clothing: colors.greenLightGradient,
  Books: colors.yellowLightGradient,
  Announcements: colors.violetLightGradient,
  FREE: colors.greenLightGradient,
  FitnessEquipment: colors.orangeLightGradient,
  'Home & Garden': colors.greenLightGradient,
  'Hunting & Fishing': colors.yellowLightGradient,
  Industrial: colors.indigoLightGradient,
  Livestock: colors.greenLightGradient,
  'Musical Instruments': colors.violetLightGradient,
  'Outdoors & Sporting': colors.greenLightGradient,
  'Recreational Vehicles': colors.orangeLightGradient,
  Tickets: colors.redLightGradient,
  Toys: colors.violetLightGradient,
  'Water Sports': colors.secondaryLightGradient,
  Weddings: colors.violetLightGradient,
  Rentals: colors.grayLightGradient,
};
